### ISSUE TITLE
Corresponding Grafana dashboard...?

### ISSUE THREAD

**Issue by ehrenfeu** [ome/omero-prometheus-tools#10]
Hi there, hope you're all good!

I'm sure you are using Grafana somewhere with this Prometheus collector - would it be possible to share a nice example dashboard with the repo?

Thanks a lot!
~Niko

**Comment by sbesson** [comment]
Hi Niko,

I guess it depends on which metric you are interested about. This Prometheus tool is deployed in every production IDR instances (via the [ome.omero_prometheus_exporter](https://galaxy.ansible.com/ome/omero_prometheus_exporter) Ansible role) and the associated Grafana dashboards are available [here](https://github.com/IDR/deployment/tree/IDR-0.9.2/ansible/grafana-dashboards) - see in particular [idr-sessions.json](https://github.com/IDR/deployment/blob/IDR-0.9.2/ansible/grafana-dashboards/idr-sessions.json) which uses the `omero_sessions_active` metrics.

**Comment by ehrenfeu** [comment]
Thanks, Sébastien! Helps a lot 😃
